internal-iface: eno12399np0

central-nodes:
  - 005-r760-ff58u10.anl.eng.rdu2.dc.redhat.com

tester-node:
  name: 005-r760-ff58u10.anl.eng.rdu2.dc.redhat.com
  ssh_key: /root/.ssh/id_ed25519

worker-nodes:
  - 005-r760-ff58u10.anl.eng.rdu2.dc.redhat.com
  - 006-r760-ff58u12.anl.eng.rdu2.dc.redhat.com
